name: capturador_datos_offline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.8.3

  amplify_flutter: ^2.0.0
  amplify_api: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

   // Pa la rachitaaaaa
flutter:
  fonts:
    - family: Typographica
      fonts:
        - asset: "assets/Fonts/TypoGraphica.otf"
    - family: ChampagneLimousinesBold
      fonts:
        - asset: "assets/Fonts/Champagne & Limousines.ttf"
    - family: FuturaBold
      fonts:
        - asset: "assets/Fonts/Futura Bold.otf"

  uses-material-design: true